apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer
  namespace: roboshop
  labels:
    name: multicontainer
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep","1000"]